name: test ssh

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo Hello, world!
        # 使用 node
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
      - name: Install npm dependencies
        run: npm install
      - name: Run build task
        run: npm run build --if-present
      - name: Test
        run: |
          ls
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
            SSH_PRIVATE_KEY: ${{ secrets.TEST_SSH_TOKEN }}
            ARGS: "-avz --delete"
            SOURCE: "build/"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: ${{ secrets.TARGET }}
